services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - 'JWT_SECRET=${JWT_SECRET}'
    container_name: burger-minute-app
    user: root
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.burgerminute.rule=Host(`burgerminute.giize.com`)"
      - "traefik.http.routers.burgerminute.entrypoints=websecure"
      - "traefik.http.routers.burgerminute.tls.certresolver=letsencrypt"
      - "traefik.http.services.burgerminute.loadbalancer.server.port=3000"
      - "traefik.http.routers.burgerminute-http.rule=Host(`burgerminute.giize.com`)"
      - "traefik.http.routers.burgerminute-http.entrypoints=web"
      - "traefik.http.middlewares.burgerminute-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.burgerminute-http.middlewares=burgerminute-redirect"
    env_file:
      - .env
    environment:
      - 'DATABASE_URL=postgresql://burger:burger_secret@db:5432/burger_minute'
      - 'UPLOAD_DIR=/app/upload'
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - 'uploads_data:/app/upload'
    restart: unless-stopped
